### ISSUE TITLE
Move cloudstateio/cloudstate/go-support into this repository

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#1]
According to https://github.com/cloudstateio/cloudstate/pull/103#issuecomment-535875322
- [x] close [PR 103](https://github.com/cloudstateio/cloudstate/pull/103) and link it for reference in a new PR in this repository
- [x] build it on travis-ci => [![Build Status](https://travis-ci.com/marcellanz/go-support.svg?branch=feature%2Fgo-support)](https://travis-ci.com/marcellanz/go-support)
- [x] the CloudState Go Language Documentation should remain in the main CloudState repository
  - ready for PR as soon as this issue is resoved https://github.com/marcellanz/cloudstate/tree/feature/go-support_go_paradox_doc
- [x] separate [cloudstateio/cloudstate/go-support](https://github.com/marcellanz/cloudstate/tree/feature/go-support) into its own repository

**Comment by marcellanz** [comment]
work in progress goes on in: [https://github.com/marcellanz/go-support/tree/feature/go-support](https://github.com/marcellanz/go-support/tree/feature/go-support)

**Comment by viktorklang** [comment]
Good stuff, @marcellanz! @jroper is on a break, but let me know what you need and I'll do my best to assist!

**Comment by marcellanz** [comment]
I think I'm good for the time @viktorklang. I can work on the tasks mentioned in the Issue and until I PR I think I need nothing yet from yours. Thank you.

**Comment by viktorklang** [comment]
Awesome, thanks @marcellanz! :)

**Comment by marcellanz** [comment]
Input from the Weekly Call, 2019-10-01:

- [x]  provide/publish a docker image for the TCK to be running on its own TCK run => #2 
   "tell" the TCK where to find them
- [x]  the CloudState protocol with its protobufs can be provided to language support libs as a versioned artefact. possibly a ZIP file. Language implementations then can decide how to distribute them with their releases => see https://github.com/cloudstateio/cloudstate/issues/118
- [x]  try to reduce source code included in the documentation, but what is there should be automatically verified

**Comment by marcellanz** [comment]
Tasks left from this issues where moved to separate issues #2, #3 and #4.

**Comment by marcellanz** [comment]
done
