### ISSUE TITLE
Move the tck shopping_cart docker image to a cloudstate owned repository

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#15]
Currently, the main cloudstate tck will run the go tck binary off of an image on an external gcr.io.

**Comment by viktorklang** [comment]
@jroper Would you have a suggestion for how we would do this?
-- 
Cheers,
√

**Comment by jroper** [comment]
Well, we'd need to work out when/how often it gets published. Do we deploy it on every push to master? On each release?

**Comment by viktorklang** [comment]
@jroper Great question(s). Would it make sense to run it when a specific tag is updated? Then we could easily trigger them manually.

**Comment by marcellanz** [comment]
This was fixed with https://github.com/cloudstateio/cloudstate/pull/325
