### ISSUE TITLE
Add devcontainer support

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#35]
Add `devcontainer`support.
Proposed docker image name would be: `cloudstateio/go-support-devcontainer:latest`

**Comment by marcellanz** [comment]
@pvlugter could you please create the DockerHub repository for the devcontainer image and add or provide the DockerHub Token for travis? Thanks.

**Comment by pvlugter** [comment]
I've added a docker hub repository. Given the naming conventions for other images, I've used `cloudstateio/cloudstate-go-devcontainer`. I don't have the credentials for cloudstatebot on docker hub, so I'll need to get them before encrypting for Travis. You should have permissions to push directly for now.

**Comment by marcellanz** [comment]
thanks, @pvlugter. I changed the image name and pushed the initial image.

**Comment by marcellanz** [comment]
implememted with: https://github.com/cloudstateio/go-support/commit/24e5523294efb6e540c5680e12c167dcbd51f65d

**Comment by pvlugter** [comment]
Here's the Travis encrypted docker hub password for cloudstatebot, in a `DOCKER_PASSWORD` env var:

```
# Docker hub password; encrypted with: travis encrypt --pro -r cloudstateio/go-support DOCKER_PASSWORD={password}
- secure: "OMwsvgBLGl+804bEIo9UigU9EDz3jnKR3oCkowbzfeT+yGb/aGqUFBBBw6fzruaB3h8Uyhe1wQUgAOwEE7xMQmNhKvHEYW0esQZQHmGeUgyCyeelh5U7iamivokXnCx2zhRj+kgd4gQE+RCunhqDcHNXGxDEf1GmQ0U/HAYVNyt6jEOVEEqb0UiG0NkTO6wRcw5fJsNrb1kPRHBM5OkoVlSNwu90kVlDgo/MPbEaNw1qkx52cA1FrTuBap4sHZNXs4BRFAoIivJNrHhrjiz41jdblcmBPLnL6hkGUguJKCBTxyuKInRKI4/grU47yg/0KNqjGOOF1MZcNbp1e09vZ1TDLHxYj4Qy3hclJTrpemcT5xdoud4nsIVyAFstR1xm2J6iKNJ+qz85wWYhxfgk8o3MJFepYqEZsNaDfGd/lWHYRXml5UJwlwA5eG/D6Q6CKn4qF1DUn5+yLgsO73MQ1qAMADgp1dhkhHELcs94w8GOWCvaNy7Zt4fKpEOLc1ThCnKQYjXQ3zOsEcciuoYtK0QxgaqpHgnvNZcZOB3H/iBkdnNW3YaQUl2+4Ooq/JmYissj6GXD1NbP5xNCEThFCGsroHm6OAJRM3BaWmna6DBworwg+lr6PMyn9fVhbOJKaH5wdfwQXOFwQ798rxK6n/oZVIBSztHhY29JNCZMtoo="
```
