### ISSUE TITLE
Dead links in new antora documentation

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#48]
There are dead links in new antora documentation:
- https://pkg.go.dev/github.com/cloudstateio/go-support/cloudstate/cloudstate#RegisterEventSourced

**Comment by pvlugter** [comment]
There is the `make validate-links` command, which checks external links, but the link checker doesn't yet support links with variables (https://github.com/gaurav-nelson/asciidoc-link-check/issues/16)

**Comment by marcellanz** [comment]
Thanks, cool.

>the link checker doesn't yet support links with variables

yeah, it doesn't catch `{cloudstate-go-lib-api-base}/cloudstate/crdt#EntityHandler.Default[`crdt.EntityHandler.Default`]` I see.
